Repository dhruvdev01/Nuxt-app, pull requests merged in 2022-10, with the labels that each got.

#1 Update index.vue
  pages/index.vue
Labels: good first issue, hacktoberfest

#2 update text
  pages/index.vue
Labels: enhancement, good first issue, hacktoberfest

#3 npm-update
  README.md
Labels: bug, good first issue, hacktoberfest, hacktoberfest-accepted

#4 pera_detail_edited
  pages/index.vue
Labels: bug, enhancement, good first issue, hacktoberfest, hacktoberfest-accepted
